
baseURL=https://stagingv3.zuperpro.com/login
browser=chrome
company_Name=fourseasons
username=suriyapathy.b@zuper.co
password=password
jobTitle=validation job
jobCategory=Plumbing Service Call
customerName=Alan zuper
userName=Sales- FE
jobDueDate=07/03/2025
scheduledToUpdate=Scheduled
acceptedToUpdate=Accepted
enRouteToUpdate=En Route
ArrivedToUpdate=Arrived
currentStatusName_Waiting=Waiting
StartingAssessmentToUpdate=Starting Assessment
currentStatusName_New_ReadytoAssign=New-Ready to Assign
currentStatusName_Scheduled=Scheduled
AssessmentCompletedToUpdate=Assessment Completed
StagingLocation=Bridgeview
futureJobLength=Estimated 3/4 Day Job
ifNoAppointmenthasbeenset=TBD Based on Client Schedule
appointmentType_PlumbingSiteVisit=This Job requires a Foreman to go back out and assess. (SV)
appointmentType_PlumbingRodding=This job requires a Drain Tech to go back out and assess. (RD)
appointmentType_PlumbingServiceCall=This job requires a Plumber to go back out and assess. (P)
NotetoAccountManagerescriptionofwork=testnotes
futureJobLength_WithProject=2 or More Days Project (Estimated to require multiple days, including inspections)
basicDescriptionofwork=testdescription
childJobCategoryPlumbingInstall=Plumbing Install
childJobCategoryPlumbingSiteVisit=Plumbing Site Visit
childJobCategoryPlumbingRodding=Plumbing Rodding
childJobCategoryPlumbingServiceCall=Plumbing Service Call
childJobCategoryPlumbingReturnVisit=Plumbing Return Visit
childJobCategoryPlumbingReturnExcavation=Plumbing Excavation
JobTBDReason=Waiting on Permit
permit_Needed=Yes
currentStatusName_JobPending=Job is Pending
currentStatusName_DispatchApprovalNeeded=Dispatch Approval Needed
job_CountForSignleJOb=1
job_CountForTwoJOb=2
twochildJobCategoryPlumbingInstall=Plumbing Install,Plumbing Rollover Job
twochildJobCategoryPlumbingReturnVisit=Plumbing Return Visit,Plumbing Rollover Job
twochildJobCategoryPlumbingExcavationVisit=Plumbing Excavation,Plumbing Rollover Job
arrivalTimeframe=8AM - 12PM Arrival